import { Command } from "./useCommand.types";
import { Hotkey } from "../useHotkey/useHotkey.types";

export const COMMAND_SHORTCUTS: Record<Command, Hotkey | Hotkey[]> = {
  copy: "ctrl+c",
  paste: "ctrl+v",
  cut: "ctrl+x",
  selectAll: "ctrl+a",
  undo: "ctrl+z",
  redo: ["ctrl+y", "ctrl+shift+z"],
  save: "ctrl+s",
  find: "ctrl+f",
  replace: "ctrl+h",
  newItem: "ctrl+n",
  open: "ctrl+o",
  print: "ctrl+p",
  close: ["ctrl+w", "escape"],
  zoomIn: ["ctrl+=", "ctrl+shift+="],
  zoomOut: "ctrl+-",
  resetZoom: "ctrl+0",
  toggleFullscreen: ["f11", "ctrl+shift+f"],
  toggleSidebar: "ctrl+b",
  help: ["f1", "ctrl+shift+h"],
  escape: "escape",
  delete: ["delete", "backspace"],
  duplicate: "ctrl+d",
  moveUp: "ctrl+arrowup",
  moveDown: "ctrl+arrowdown",
  indent: "tab",
  outdent: "shift+tab",
  saveAs: "ctrl+shift+s",
  export: "ctrl+e",
  import: "ctrl+i",
  goBack: ["ctrl+arrowleft", "alt+arrowleft"],
  goForward: ["ctrl+arrowright", "alt+arrowright"],
  refresh: ["f5", "ctrl+r"],
  toggleDarkMode: "ctrl+shift+d",
  showSettings: "ctrl+,",
  searchGlobal: "ctrl+shift+f",
  formatCode: "ctrl+shift+i",
  comment: "ctrl+/",
  share: "ctrl+shift+s",
  pageUp: "pageup",
  pageDown: "pagedown",
};

export const MAC_COMMAND_SHORTCUTS: Record<Command, Hotkey | Hotkey[]> = {
  copy: "meta+c",
  paste: "meta+v",
  cut: "meta+x",
  selectAll: "meta+a",
  undo: "meta+z",
  redo: "meta+shift+z",
  save: "meta+s",
  find: "meta+f",
  replace: "meta+shift+f",
  newItem: "meta+n",
  open: "meta+o",
  print: "meta+p",
  close: ["meta+w", "escape"],
  zoomIn: ["meta+=", "meta+shift+="],
  zoomOut: "meta+-",
  resetZoom: "meta+0",
  toggleFullscreen: ["meta+ctrl+f", "f11"],
  toggleSidebar: "meta+shift+b",
  help: ["f1", "meta+shift+h"],
  escape: "escape",
  delete: ["delete", "backspace"],
  duplicate: "meta+d",
  moveUp: "meta+arrowup",
  moveDown: "meta+arrowdown",
  indent: "tab",
  outdent: "shift+tab",
  saveAs: "meta+shift+s",
  export: "meta+e",
  import: "meta+i",
  goBack: ["meta+arrowleft", "meta+["],
  goForward: ["meta+arrowright", "meta+]"],
  refresh: ["meta+r", "f5"],
  toggleDarkMode: "meta+shift+d",
  showSettings: "meta+,",
  searchGlobal: "meta+shift+f",
  formatCode: "meta+shift+i",
  comment: "meta+/",
  share: "meta+shift+s",
  pageUp: "pageup",
  pageDown: "pagedown",
};
