import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.scss";

import '../ui/globals.css'
import { cookies } from "next/headers";

const inter = Inter({
  variable: "--font-family",
  subsets: ["latin"],
});

const mono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const theme = cookieStore.get('theme')

  return (
    <html lang="en" style={{ colorScheme: theme?.value }} className={theme?.value ?? ''}>
      <body className={`${inter.variable} ${mono.variable}`}>
        {children}
      </body>
    </html>
  );
}
