import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import '../ui/globals.css'

const inter = Inter({
  variable: "--font-family",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
